### ISSUE TITLE
dune/jbuilder support unreleased?

### ISSUE THREAD

**Issue by timbertson** [ocaml-ppx/ppx_deriving_protobuf#23]
I'm not very clear on PPX actually works, so apologies if I'm just doing it wrong. But here's my sample code:

```
$ cat dune
(executable
	(name rpc)
	(preprocess (pps ppx_deriving_protobuf))
)

$ cat rpc.ml
type t = int [@@deriving protobuf]

let () =
	Printf.printf "%S\n" (Bytes.to_string (Protobuf.Encoder.encode_exn to_protobuf 1))
```

With ocaml 4.06.1 and ppx_deriving_protobuf 2.6 (in a fresh opam switch), running this gives me:

```
$ jbuilder build rpc.exe
# ( ... )
File "rpc.ml", line 4, characters 40-67:
Error: Unbound module Protobuf
```

If I peek in `_build/log` and use the same ppx command executable to dump the output, I see it's not actually generating any code:

```
$ (cd _build/default && .ppx/e62b9ba70091960bbddb1d98645d590a/ppx.exe -o /dev/stdout --impl rpc.ml)
type t = int[@@deriving protobuf]
let () =
  Printf.printf "%S\n"
    (Bytes.to_string (Protobuf.Encoder.encode_exn to_protobuf 1))
```

After I `opam pin add ppx_deriving_protobuf git@github.com:ocaml-ppx/ppx_deriving_protobuf.git`, it works:

```
$ jbuilder build rpc.exe
$ ./_build/default/rpc.exe 
"\b\001"
```

Looking at the git log, I'm guessing the port to jbuilder (c5ece555e6ab9553882bd61adbfef9a4d37e5509) also makes the library work in jbuilder/dune, but that's ahead of the latest v2.6. Any chance of a release?

Side note: there's a warning about an unused `rec` in `from_protobuf`, which `dune` turns into an error (which is why I used the `jbuilder` command as a workaround).

**Comment by XVilka** [comment]
It makes sense to prepare the release to support newer OCaml and ppx-deriving versions, once released: https://github.com/ocaml/opam-repository/pull/14454

**Comment by XVilka** [comment]
Now ppx_deriving and ppx_deriving_yojson were released and updated in opam repository, nothing stops from the releasing new version of ppx_deriving_protobuf, I think.

**Comment by XVilka** [comment]
Would be possible to craft a new release once https://github.com/ocaml-ppx/ppx_deriving_protobuf/pull/26 is merged.

**Comment by XVilka** [comment]
@gasche can you please release a new version with 4.08 support?

**Comment by gasche** [comment]
I'm in holidays right now; please feel free to ping me again in a couple days if I haven't sent more signal.

**Comment by XVilka** [comment]
Thanks to @gasche it can be closed now.
