### ISSUE TITLE
Port to ppxlib

### ISSUE THREAD

**Issue by XVilka** [ocaml-ppx/ppx_deriving_protobuf#28]
To reduce the maintenance needed for upgrading the compiler version.
See also https://github.com/ocaml-ppx/ppx_deriving/issues/203 and https://github.com/ocaml-ppx/ppx_deriving_yojson/issues/103

**Comment by XVilka** [comment]
See https://github.com/ocaml-ppx/ppx_deriving/pull/206

**Comment by XVilka** [comment]
Now ppx_deriving [has been ported](https://github.com/ocaml-ppx/ppx_deriving/commit/0525a85b5ccd92ec3edf287526cf9100df12e68e) to ppxlib, it's time to port also ppx_deriving_protobuf.

**Comment by XVilka** [comment]
Ppx_deriving_yojson also[ was ported to ppxlib](https://github.com/ocaml-ppx/ppx_deriving_yojson/pull/121).

**Comment by kit-ty-kate** [comment]
Fixed by https://github.com/ocaml-ppx/ppx_deriving_protobuf/pull/39
